---
- hosts: all
  #serial: 50
  gather_facts: False
  become: yes
  tasks:
  - name: ensure xymon-client is the latest version
    yum:
      name: xymon-client
      state: latest
      enablerepo: mi-tech-test
      update_cache: yes
    notify:
     - run cfengine
     - restart xymon-client
  handlers:
    - name: run cfengine
      command: /usr/sbin/cf-agent -IKC
    - name: restart xymon-client
      service:
        name: xymon-client
        state: restarted
